import "../components/common/Header";
import "../components/common/Layout";
import "../components/common/SideNavigation";
import "../components/common/Footer";
import "../components/common/Login";

import "../components/product/productcategoriesscreen/ProductCategoriesScreen";
import "../components/product/productcategoriesscreen/CategoryList";
import "../components/product/productlistscreen/ProductListScreen";
import "../components/product/productlistscreen/ProductList";
import "../components/product/productscreen/ProductScreen";
import "../components/product/productscreen/ProductDetails";
import "../components/shoppingcart/shoppingcartscreen/ShoppingCartScreen";
import "../components/shoppingcart/shoppingcartscreen/ShoppingCartProductList";
import "../components/shoppingcart/shoppingcartscreen/ShoppingCartTotalDetails";
import "../components/shoppingcart/checkoutscreen/CheckoutScreen";
import "../components/shoppingcart/checkoutscreen/CustomerInformationForm";
import "../components/shoppingcart/checkoutscreen/PaymentInformationForm";
import "../components/shoppingcart/paymentconfirmationscreen/PaymentConfirmationScreen";
